### ISSUE TITLE
npm install - invalid version: "1"

### ISSUE THREAD

**Issue by NickHath** [DevMountain/angular-2-afternoon#3]
I was having difficulties running npm install with "version": "1" in the package.json.

Changing it to "version": "0.0.1" solved the issue. I think npm was expecting 3 digits separated by . when parsing version numbers. Here's a [helpful link](https://stackoverflow.com/questions/27543013/npm-install-fails-invalid-version).

**Comment by devlemire** [comment]
Fixed.
